### PR TITLE
Added Support for React Native Projects

### PR DESCRIPTION
**Pull request by prscX**
Hi @GrenderG, 

First of all I would like to appreciate for creating such a cool toast library.

I have created a React Native bridge plugin for using this library with React Native projects.

I have added the same in `README`. Can you please merge this request so that if someone looking to use this library for React Native projects can easily do the same.

Please let me know in case any changes are required

[react-native-toasty](https://github.com/prscX/react-native-toasty)

Thanks
Pranav

### CODE REVIEW

**Comment by GrenderG** [comment]
Thanks for this wrapper, but please, don't use the same icon as `Toasty`.

**Comment by prscX** [comment]
Hi @GrenderG, I have changed the icon, please let me know incase any other changes are recommended.

Thanks
</ Pranav >

**Comment by GrenderG** [comment]
Change the text to "`You may now use this library with [React Native](https://github.com/facebook/react-native) via this [module](https://github.com/prscX/react-native-toasty).`" And it will be ready to merge.

**Comment by GrenderG** [comment]
Thanks for your contribution!

**Pull request merged**
