### PR TITLE
Enhancement - show messsage from resource #67

### PR DESCRIPTION
**Pull request by anandkumarkparmar**

### CODE REVIEW

**Comment by anandkumarkparmar** [comment]
Hi @GrenderG, please review the PR. Let me know if I missed anything. Thanks.

**Comment by anandkumarkparmar** [comment]
Hi @GrenderG, I made the change. Please review it. Thanks.

**Comment by GrenderG** [comment]
Merged, thanks for your contribution!

**Comment by anandkumarkparmar** [comment]
@GrenderG Welcome. 
I am Beginner in Open Source community. Suggest me few projects, where I can contribute more.

**Pull request merged**
