### PR TITLE
Fix #110

### LINKED ISSUE #110: Toast not showing in some devices
Hi, one of my clients with ASUS Z00AD, Android 6.0.1 told me that he is not able to see toast messages. I can not reproduce this situation in my test devices or emulators but he send me the video that does not show any toast message in where it has to. So is there any suggestion with this issue? (Used toasty version: 1.4.1)

### PR DESCRIPTION
**Pull request by ryuunoakaihitomi**

### CODE REVIEW

**Comment by GrenderG** [comment]
Can you please explain what the code you added is doing? (Also, maybe use a more descriptive name for the method).

Thanks.

**Comment by ryuunoakaihitomi** [comment]
@GrenderG 
There are 2 unrelated bugs in Toast, but their solutions must be combined in order to repair it non-invasively.
I am not quite proficient with naming, so I have no idea for more descriptive name. You can merge this PR and rename it later.

In short, these solutions use [dynamic proxy](https://docs.oracle.com/javase/8/docs/technotes/guides/reflection/proxy.html) to fix.

## Cannot show toast without notification permission
* Toast
```java
    public void show() {
        if (mNextView == null) {
            throw new RuntimeException("setView must have been called");
        }

        // ATTENTION:
        // NotificationManagerService, AIDL: INotificationManager
        // We can use dynamic proxy here.
        INotificationManager service = getService();
        // ATTENTION: Parameter[0]: package name.
        String pkg = mContext.getOpPackageName();
        // ATTENTION: Parameter[1]: TransientNotification.
        TN tn = mTN;
        tn.mNextView = mNextView;
        final int displayId = mContext.getDisplayId();

        try {
            // ATTENTION: Go to NotificationManagerService.enqueue(...)
            service.enqueueToast(pkg, tn, mDuration, displayId);
        } catch (RemoteException e) {
            // Empty
        }
    }
```
* NotificationManagerService
```java
    @Override
    public void enqueueToast(String pkg, ITransientNotification callback, int duration)
    {
        if (DBG) {
            Slog.i(TAG, "enqueueToast pkg=" + pkg + " callback=" + callback
                    + " duration=" + duration);
        }

        if (pkg == null || callback == null) {
            Slog.e(TAG, "Not doing toast. pkg=" + pkg + " callback=" + callback);
            return ;
        }
        // ATTENTION: System Toast: "android".equals(pkg)
        final boolean isSystemToast = isCallerSystemOrPhone() || ("android".equals(pkg));
        final boolean isPackageSuspended =
                isPackageSuspendedForUser(pkg, Binder.getCallingUid());

        // ATTENTION: Check notification permission.
        if (ENABLE_BLOCKED_TOASTS && !isSystemToast &&
                (!areNotificationsEnabledForPackage(pkg, Binder.getCallingUid())
                        || isPackageSuspended)) {
            Slog.e(TAG, "Suppressing toast from package " + pkg
                    + (isPackageSuspended
                    ? " due to package suspended by administrator."
                    : " by user request."));
            return;
        }
        ...
```
## BadTokenException
Here‘s a solution that describes the cause of the bug in detail. [ToastCompat](https://github.com/PureWriter/ToastCompat/)
But it's invasive, we have to replace all existing Toasts to fix the bug.
Inspired by [this article](https://www.jianshu.com/p/c8e00943afc9), I change the hook point and use dynamic proxy in order to make less invasive.

**Comment by ryuunoakaihitomi** [comment]
I wonder th

**Comment by ryuunoakaihitomi** [comment]
Why not merge my pr or just give me a response? Did I do something wrong?

**Comment by GrenderG** [comment]
Haven't had time yet to review your code, sorry!

**Comment by ryuunoakaihitomi** [comment]
It's OK. I don't think it will take long to review this code, but I am still pleasant to receive your reply.

**Comment by ryuunoakaihitomi** [comment]
It's OK. I don't think it will take long to review this code, but I'm still pleased to receive your reply.

**Comment by codinghasan** [comment]
Hi I'm pretty new about Android development! I was just trying to learn how
to add a new library and I used your toasty library, it looks pretty good.
I'll give you a star.
Have a nice day

29 Ağu 2020 Cmt 07:47 tarihinde ZQY <notifications@github.com> şunu yazdı:

**Comment by codinghasan** [comment]
I'm just a student, actually I don't understand what are you taking about. "Why
not merge my pr or just give me a response? Did I do something wrong?". Please
can you explain this sentence to me cause I have checked out. I already
give you a star and fork.

Have a nice day!

29 Ağu 2020 Cmt 16:08 tarihinde gezginko <codinghasan@gmail.com> şunu yazdı:

**Pull request closed without merging**
