### PR TITLE
Migrated from Support to AndroidX

### PR DESCRIPTION
**Pull request by ChintanRathod**
- Replaced older support dependencies with AndroidX
- Simplify dependencies

### CODE REVIEW

**Comment by GrenderG** [comment]
Hello, now that AndroidX is widely used, I'm happy to merge this PR, would you mind updating it to the current version numbers? Thanks.

**Comment by ChintanRathod** [comment]
> Hello, now that AndroidX is widely used, I'm happy to merge this PR, would you mind updating it to the current version numbers? Thanks.

Did upgrade the AndroidX version. Kindly check.

**Comment by jakoss** [comment]
Could you release version with that? This library is last one stopping us to drop jetifier completely

**Comment by ChintanRathod** [comment]
Well Jetifier requires for AndroidX. Have to check if we can use that without it or not. Is that the problem we are not able to remove Jetifier from the gradle system?

**Comment by jakoss** [comment]
Jetifier is a tool that automatically changes libraries that does not support androidX to work with our app. If all libraries are based on androidX you can stop jetifier with a significant gain on build performance: https://adambennett.dev/2020/08/disabling-jetifier/

**Comment by ChintanRathod** [comment]
That's nice. I am mistaken to know Jetifier. Thanks for sharing the blog. I will refer and let's try to implement the same in this library as well.

**Comment by jakoss** [comment]
Great, but in the mean time can you release a new version of toasty with this pull request merged? This will solve the issue for us

**Comment by ChintanRathod** [comment]
This would be addressed to the owner of the library.

**Comment by GrenderG** [comment]
Version 1.5.0 has been released, you can use it now @jakoss. As a side note, remember that you can import any commit, you don't need to wait for me to publish a stable release.
image
https://jitpack.io/#GrenderG/Toasty/

**Comment by jakoss** [comment]
Awesome, thanks!

**Pull request merged**
