### PR TITLE
added library information via POM

### PR DESCRIPTION
**Pull request by cyb3rko**
I tried to include the library information and definition which was mentioned in #137.

I hope it will work!

### CODE REVIEW

**Comment by GrenderG** [comment]
Thanks!

**Comment by cyb3rko** [comment]
Will you publish a beta version or how can we test it?

**Comment by GrenderG** [comment]
Yes, I'll update the library soon.

**Comment by cyb3rko** [comment]
Roger

**Comment by cyb3rko** [comment]
I already tested it aaaand... it doesn't work yet.
Please reopen this issue, then I will rework this whole thing...

**Comment by GrenderG** [comment]
I haven't published the new version yet.

**Comment by cyb3rko** [comment]
Yeah, but you can test it by using commits as the version:

**Comment by cyb3rko** [comment]
Have you published the library via JitPack?

**Comment by cyb3rko** [comment]
Btw: It works and I just did not test it properly.

**Pull request merged**
